(module $m3
    (func $is_even (param $n i32) (result i32)
        (if (result i32)
            (i32.eqz (local.get $n))
            (then (i32.const 1) (call $is_odd))
            (else (i32.sub (local.get $n) (i32.const 1)))
        )
    )
    (func $is_odd (param $n i32) (result i32)
        (if (result i32)
            (i32.eqz (local.get $n))
            (then (i32.const 0) (call $is_even))
            (else (i32.sub (local.get $n) (i32.const 1)))
        )
    )
)